project 2 commerce/commerce/auctions/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "auctions"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view , name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create", views.createlisting, name="createlisting"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("closelistings", views.closelistings, name="closelistings"),
    path("listing/<int:listingID>", views.listing, name="listing"),
    path("comment/<int:listingID>", views.saveComment, name = "saveComment"),
    path("category" , views.category, name="category"),
    path("category/<str:categoryName>", views.category, name="categoryListings"),
    path("user/<str:username>", views.userProfile, name="userProfile")
]

project 2 commerce/commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project 2 commerce/commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    
    def __str__(self):
        return self.username
    
    

class ListingInformation(models.Model):
    title = models.CharField(max_length=64)
    description = models.TextField(max_length=200)
    bidCurrentPrice = models.FloatField()
    image = models.ImageField(blank=True, upload_to="auctions/images/")
    category = models.CharField(max_length=64, blank=True, null=True)
    lister = models.ForeignKey(User, on_delete=models.CASCADE , related_name="listings")
    time = models.DateTimeField(auto_now_add=True)
    isListingOpen = models.BooleanField(default=True)
    winner =  models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f"{self.title} listed by {self.lister}"


class Comment(models.Model):
    content = models.CharField(max_length=120)
    writer = models.ForeignKey(User, on_delete=models.CASCADE,  related_name="comments")
    listing = models.ForeignKey(ListingInformation, on_delete=models.CASCADE, related_name="comments")
    time = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.writer}: {self.content}"



class Bid(models.Model):
    bidder = models.ForeignKey(User, on_delete=models.CASCADE, related_name="biddings")
    listing = models.ForeignKey(ListingInformation, on_delete=models.CASCADE, related_name="bids")
    bidPrice = models.FloatField()

    def __str__(self):
        return f"Bid of {self.bidPrice} by {self.bidder} on {self.listing}"
    
class Watchlist(models.Model):
    listing = models.ForeignKey(ListingInformation, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="watchlist")

    def __str__(self):
        return f"Listing: {self.listing}, watchlisted by {self.user}"

project 2 commerce/commerce/auctions/forms.py
from django import forms
from .models import ListingInformation


class ListingForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control mb-3'
            visible.field.widget.attrs['placeholder'] = visible.field.label


    class Meta:
        labels = {
            "title":"Title",
            "description":"Description",
            "bidCurrentPrice":"Initial Bid",
            "image":"Item Image",
            "category":"Category"
        }
        model = ListingInformation
        fields = ['title', 'description', 'bidCurrentPrice', 'image', 'category']

project 2 commerce/commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .forms import ListingForm
from .models import User, ListingInformation, Watchlist, Bid, Comment
from .util import *

def index(request):
    return render(request, "auctions/index.html", {
        "listings": ListingInformation.objects.filter(isListingOpen = True).all(),
        "message": "Active Listings"
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")

@login_required
def createlisting(request):
    if request.method == "POST":
        form  = ListingForm(request.POST, request.FILES)

        if form.is_valid():
            listinginformation = form.save(commit=False)
            listinginformation.lister = request.user
            listinginformation.save()
            return HttpResponseRedirect(reverse("auctions:index"))
        
    else:
        form = ListingForm()

    return render(request, 'auctions/createlisting.html', {
        "ListingForm": form
    })


def listing(request, listingID):
    listingObj = ListingInformation.objects.get(pk = listingID)
    message=""
    watchlisted, creatorIsViewingTheList = getRequestFlags(request, listingID)
    


    if request.method == "POST":
        isBidingForm = int(request.POST["isBidingForm"])
        if isBidingForm:

            price = float(request.POST["bidPrice"])

            if(price <= listingObj.bidCurrentPrice):
                message = "Bid Not Placed. Bid price is less than the current price of the listing"
            else:
                listingObj.bidCurrentPrice = price
                listingObj.save()
                newBid = Bid(bidPrice = price, bidder = request.user, listing = listingObj)
                newBid.save()

        else:

            listingObj.isListingOpen = 0 
            listingObj.winner = getCurrentBidder(listingID)
            listingObj.save()
        

    currentBidder = getCurrentBidder(listingID)

    return render(request, "auctions/listing.html", {
        "listing": listingObj,
        "watchlisted": watchlisted,
        "creatorIsViewingTheList": creatorIsViewingTheList,
        "message":message,
        "numBids": Bid.objects.filter(listing_id = listingID).count(),
        "currentBidder": currentBidder,
        "comments": listingObj.comments.all()
    })

@login_required
def watchlist(request):
    if request.method == "POST":
        pleaseWatchlist = int(request.POST["pleaseWatchlist"])
        listingID = int(request.POST["listing_id"])
        if pleaseWatchlist:
            w = Watchlist(user=request.user, listing_id = listingID)
            w.save()
        else:
            w = Watchlist.objects.filter(user=request.user, listing_id = listingID)
            w.delete()
        
        return HttpResponseRedirect(reverse("auctions:listing", args=(listingID, )))

    return render(request, "auctions/index.html", {
        "message": "Watchlist",
        "watchlist": Watchlist.objects.filter(user = request.user).all(),
        "isWatchlist": 1
    })

@login_required
def saveComment(request, listingID):
    listingObj = ListingInformation.objects.get(pk = listingID)

    if request.method == "POST":
        commentContent = request.POST["comment"]

        newComment = Comment(content = commentContent, writer = request.user, listing = listingObj)
        newComment.save()

        return HttpResponseRedirect(reverse("auctions:listing", args=(listingID, )))


def closelistings(request):
    return render(request, 'auctions/index.html', {
        "listings": ListingInformation.objects.filter(isListingOpen = False).all(),
        "message": "Close Listings"
    })

def category(request, categoryName = None):
    if not categoryName:
        categories = []
        allListingsWithCategory = ListingInformation.objects.exclude(category__isnull=True).exclude(category__exact='').filter(isListingOpen = True)
        for listing in allListingsWithCategory:
            if listing.category not in categories:
                categories.append(listing.category)
        
        return render(request, 'auctions/category.html', {
            "categories": categories
        })
    else:
        categoryListings = ListingInformation.objects.filter(category = categoryName).filter(isListingOpen = True)
        return render(request, 'auctions/index.html', {
            "message": f"Category Listing: {categoryName}",
            "listings": categoryListings
        })

def userProfile(request, username):

    user = User.objects.get(username = username)

    listings = user.listings.all()

    return render(request, 'auctions/user.html', {
        "userInfo":user,
        "activeListings":listings.filter(isListingOpen = 1),
        "closeListings":listings.filter(isListingOpen = 0)
    })

project 2 commerce/commerce/auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% block body %}

    <!-- <h4>Categories:</h4> -->
    <h3 class="display-3 text-center mt-5">Categories</h1>
    <hr class="w-50 mx-auto ">

        <div class="list-group container mt-3">

            {% for category in categories %}
            
                <a class="list-group-item list-group-item-action list-group-item-warning" href="{% url 'auctions:categoryListings' category %}">{{ category }}</a>
            
            {% empty %}
                <li class="list-group-item">No Categories Listed</li>
            {% endfor %}
            
        </div>
        
{% endblock %}

project 2 commerce/commerce/auctions/templates/auctions/createlisting.html
{% extends "auctions/layout.html" %}
{% load static %}

{% block body %}

<h3 class="display-3 text-center mt-5">Create Listing</h1>
<hr class="w-50 mx-auto">
<!-- <h3>Create Listing</h3> -->

{% if message %}
<div class="text-danger">{{message}}</div>
{% endif %}

<div class="d-flex justify-content-center align-items-center">
<form enctype="multipart/form-data" action="{% url 'auctions:createlisting' %}" method="post" class="mt-3 ">
    {% csrf_token %}
    {{ListingForm}}
    <input class="btn btn-outline-warning mb-4" type="submit" value="Create Listing">
</form>
</div>


{% endblock %}

project 2 commerce/commerce/auctions/templates/auctions/layout.html
{% load static %}



<!DOCTYPE html>
<html lang="en" class="h-100" data-bs-theme="dark">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link href="{% static 'auctions/styles.css' %}" type="text/css" rel="stylesheet">
    </head>
    <body class="d-flex flex-column h-100">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        
        <!-- navbar starts -->

        <nav class="navbar navbar-expand-lg  ">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'auctions:index' %}">
        <img src="{% static 'auctions/logo.png' %}" alt="Logo" width="26" height="26" class="d-inline-block align-text-top">
        Auctions</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link text-white link-body-emphasis" aria-current="page" href="{% url 'auctions:index' %}">Active Listings</a>
        </li>

        {% if user.is_authenticated %}

        <li class="nav-item">
            <a class="nav-link text-white link-body-emphasis" href="{% url 'auctions:createlisting' %}">Create Listing</a>
        </li>

        <li class="nav-item">
            <a class="nav-link text-white link-body-emphasis" href="{% url 'auctions:watchlist' %}">Watchlist</a>
        </li>

        {% endif %}
        <li class="nav-item">
          <a class="nav-link text-white link-body-emphasis" href="{% url 'auctions:category' %}">Categories</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white link-body-emphasis" href="{% url 'auctions:closelistings' %}">Closed Listings</a>
        </li>

        
      </ul>
      
        {% if user.is_authenticated %}
        <span class="navbar-text">
                Signed in as  <a href="{% url 'auctions:userProfile' user.username%}" class="text-warning " >{{ user.username }}</a>.
            </span>
            <a href="{% url 'auctions:logout' %}"><button type="button" class="btn btn-outline-warning me-2 ms-3">Log Out</button></a>
            {% else %}
            <a href="{% url 'auctions:login' %}"><button type="button" class="btn btn-outline-warning me-2 ms-1">Login</button></a>
            <a href="{% url 'auctions:register' %}"><button type="button" class="btn btn-warning">Register</button></a>
            {% endif %}
        <!-- <button type="button" class="btn btn-outline-primary me-2 ms-1">Login</button>
        <button type="button" class="btn btn-primary">Sign-up</button> -->
    </div>
  </div>
</nav>

        <!-- navbar ends -->
          {% block body %}
           {% endblock %}
        

        <!-- footer starts here  -->

        <footer class="footer mt-auto py-3  border-top">
          <div class="container-fluid">
            <div class="row d-flex flex-wrap justify-content-between align-items-center ">
              <div class="col-md-4 d-flex align-items-center">
            <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
              <img src="{% static 'auctions/logo.png' %}" alt="Logo" width="26" height="26" class="d-inline-block align-text-top">

            </a>
            <span class="mb-3 mb-md-0 text-body-primary text-capitalize text-warning ">This App is made with  <i class="fa-solid fa-heart"></i> by <a class="text-warning" target="_blank" href="https://github.com/SaadHusayn">Saad Hussain</a>.</span>
          </div>
      
          <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3"><a class="text-white fs-4" href="https://www.linkedin.com/in/saad-hussain-b55171203/" target="_blank"><i class="fa-brands fa-linkedin"></i></a></li>
            <li class="ms-3"><a class="text-white fs-4" href="https://github.com/SaadHusayn" target="_blank"><i class="fa-brands fa-github"></i></a></li>
            <li class="ms-3"><a class="text-white fs-4" href="https://www.youtube.com/@SaadHussain56" target="_blank"><i class="fa-brands fa-youtube"></i></a></li>
          </ul>
            </div>
          </div>
          
        </footer> 

        <!-- footer ends here -->
    </body>
</html>

project 2 commerce/commerce/auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}
{% load static %}

{% block body %}




<div class="container my-5">
    <div class="row g-3">
        <div class="col-lg-6 col-12">
            <div class="d-flex align-items-center justify-content-center ">
                {% if listing.image %}
                    <img src="{{listing.image.url}}" alt="{{listing.title}}" class="img-fluid rounded-2">
                {% else %}
                    <img src="{% static 'auctions/default.png' %}" alt="{{listing.title}}" class="img-fluid rounded-2">
                {% endif %}
             </div>
        </div>

        <div class="col-lg-6 col-12 heading">
            
            <h1 class="  pb-2 border-bottom ">{{listing.title}}</h3>
            
<!-- watchlist button starts -->
            
            
            {% if user.is_authenticated %}
                <form action="{% url 'auctions:watchlist' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="listing_id" value="{{listing.id}}">
                {% if watchlisted %}
                    <input type="hidden" name="pleaseWatchlist" value="0">
                    <input class="btn btn-sm btn-outline-warning" type="submit" value="Remove From Watchlist">
                {% else %}
                    <input type="hidden" name="pleaseWatchlist" value="1">
                    <input class="btn btn-sm btn-outline-warning" type="submit" value="Watchlist">
                {% endif %}
                </form>
            {% endif %}

<!-- watchlist button ends -->


        {% if listing.isListingOpen %}

                <h3 class="my-2 text-warning">${{listing.bidCurrentPrice}}</h3>
            
                {% if user.is_authenticated %}
                    
                    {% if currentBidder %}
                        <p class="my-2">{{numBids}} bid(s) so far. <a class="hover-effect text-decoration-none" href="{% url 'auctions:userProfile' currentBidder.username %}">{{currentBidder}}</a> bid is the current bid</p>
                    {% else %}
                        <p class="my-2">{{numBids}} bid(s) so far.</p>
                    {% endif %}
            
                    {% if creatorIsViewingTheList %}
            
                        <form action="{% url 'auctions:listing' listing.id %}" method="post">
                            {% csrf_token %}
                            <input class="btn btn-outline-warning my-2"  type="submit" value="Close">
                            <input type="hidden" name="isBidingForm" value="0">
                        </form>
            
                    {% else %}
            
                        <form action="{% url 'auctions:listing' listing.id%}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="isBidingForm" value="1">
                            
                            

                            <div class="input-group my-2">
                                <input type="number" min="0" step="0.01" name="bidPrice" class="form-control" placeholder="Bid" aria-label="Bid" aria-describedby="button-addon2">
                                <button class="btn btn-outline-warning" type="submit" id="button-addon2">Place Bid</button>
                            </div>
                            
                            {% if message %}
                                <div class="my-2 text-danger-emphasis tw-bold">{{message}}</div>
                            {% endif %}
                            
                            
                        </form>
                    {% endif %}
                
                {% else %}
            
                    <a class="my-2 hover-effect"" href="{% url 'auctions:login' %}">Login to place bid on this listing.</a>
            
                {% endif %}
            
        {% else %}
        
            {% if listing.winner %}
        
                {% if listing.winner == request.user %}
                    <h5 class="my-2 text-warning" >Listing Closed at {{ listing.bidCurrentPrice }} with {{ numBids }} bid(s). You are the winner of this auction.</h5>
                {% else %}
                    <h5 class="my-2 text-warning" >Listing Closed at {{ listing.bidCurrentPrice }} with {{ numBids }} bid(s). {{ listing.winner }} is the winner of this auction.</h5>
                {% endif %}
        
            {% else %}
                <h5 class="my-2 text-warning" >Listing Closed at {{ listing.bidCurrentPrice }} with {{ numBids }} bid(s).</h5>
            {% endif %}
        
        {% endif %} 
        </div>
    </div>
</div>

<nav class="container mb-3">
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      <button class="nav-link  text-warning active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">Details</button>
      <button class="nav-link text-warning" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Comments</button>
      
    </div>
  </nav>
  <div class="tab-content container mb-3" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab" tabindex="0">
        <h5>{{listing.description}}</h5>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Listed by: <a class="text-warning" href="{% url 'auctions:userProfile' listing.lister.username %}">{{ listing.lister }}</a></li>
            {% if listing.category %}
            <li class="list-group-item">Category:  <a class="text-warning" href="{% url 'auctions:categoryListings' listing.category %}">{{listing.category}}</a></li>
            {% else %}
                <li class="list-group-item">Category: No Category Listed</li>
            {% endif %}
            <li class="list-group-item">Created On: {{listing.time}}</li> 
        </ul>
    </div>
    <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab" tabindex="0">


        <div class="row d-flex justify-content-center">
            <div class="col-md-8 col-lg-6">
              <div class="card shadow-0 border bg-warning-subtle" >
                <div class="card-body p-4">
                
                {% if user.is_authenticated %}
                    <form action="{% url 'auctions:saveComment' listing.id %}" method="post">
                        {% csrf_token %}
                        <div data-mdb-input-init class="form-outline mb-4">
                            <input type="text" name="comment" id="addANote" class="form-control" placeholder="Write Comment..." />
                        </div>
                        
                    </form>
                {% else %}
                    <a href="{% url 'auctions:login' %}" class="hover-effect">Login to write Comment on this listing.</a>
                {% endif %}
                    
                  {% for comment in comments %}

                    <div class="card mb-4">
                        <div class="card-body">
                        <p>{{comment.content}}</p>
            
                        <div class="d-flex justify-content-between">
                            <div class="d-flex flex-row align-items-center">
                            <p class="small mb-0 ms-2"><a class="hover-effect text-decoration-none" href="{% url 'auctions:userProfile' comment.writer.username %}">{{comment.writer}}</a></p>
                            </div>
                            <div class="d-flex flex-row align-items-center">
                            <p class="small text-muted mb-0">{{comment.time}}</p>
                            </div>
                        </div>
                        </div>
                    </div>
                    
                {% empty %}
                    <div class="card mb-4">
                        <div class="card-body">
                        <p>No Comments on this listing so far.</p>
                        </div>
                    </div>
                {% endfor %}

                </div>
              </div>
            </div>
          </div>


    </div>
  </div>


{% endblock %}

project 2 commerce/commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}
{% load static %}

{% block body %}


    <div class="d-flex align-items-center py-4">
        
    <main class="form-signin m-auto" style="width: 300px!important;">
      <form action="{% url 'auctions:login' %}" method="post">
        <img class="mb-4" src="{% static 'auctions/logo.png' %}" alt="" width="72" height="70">
        <h1 class="h3 mb-3 fw-normal">Please log in</h1>
        {% if message %}
             <h5 class="text-danger">{{ message }}</h5 >
        {% endif %}

        {% csrf_token %}
    
        <div class="form-floating">
          <input type="text" name="username"  autofocus class="form-control" id="floatingInput" placeholder="username" style="border-bottom-left-radius: 0;
    border-bottom-right-radius: 0;">
          <label for="floatingInput">Username</label>
        </div>
        <div class="form-floating">
          <input type="password" class="form-control" name="password" id="floatingPassword" placeholder="Password" style="border-top-left-radius: 0;
    border-top-right-radius: 0;">
          <label for="floatingPassword">Password</label>
        </div>
    
        <div class="form-check text-start my-3">
          <input class="form-check-input" type="checkbox" value="remember-me" id="flexCheckDefault">
          <label class="form-check-label" for="flexCheckDefault">
            Remember me
          </label>
        </div>
        <button class="btn btn-outline-warning w-100 py-2" type="submit">Log in</button>
      </form>
    </main>
    
    </div>
    
{% endblock %}

project 2 commerce/commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}
{% load static %}

{% block body %}


    <div class="d-flex align-items-center py-4">
        
        <main class="form-signin m-auto" style="width: 300px!important;">
          <form action="{% url 'auctions:register' %}" method="post">
            <img class="mb-4" src="{% static 'auctions/logo.png' %}" alt="" width="72" height="70">
            <h1 class="h3 mb-3 fw-normal">Register</h1>
            {% if message %}
                 <h5 class="text-danger">{{ message }}</h5 >
            {% endif %}
    
            {% csrf_token %}
        
            <div class="form-floating">
              <input type="text" name="username"  autofocus class="form-control" id="floatingUsername" placeholder="username" style="border-bottom-left-radius: 0;
        border-bottom-right-radius: 0;">
              <label for="floatingUsername">Username</label>
            </div>
            <div class="form-floating">
                <input type="email" name="email" class="form-control" id="floatingEmail" placeholder="Email" style="border-radius:0;">
                <label for="floatingEmail">Email</label>
              </div>
              <div class="form-floating">
                <input type="password" name="password"  class="form-control" id="floatingPassword" placeholder="Password" style="border-radius:0;">
                <label for="floatingPassword">Password</label>
              </div>
            <div class="form-floating">
              <input type="password" class="form-control" name="confirmation" id="floatingPasswordConfirmation" placeholder="Confirm Password" style="border-top-left-radius: 0;
        border-top-right-radius: 0;">
              <label for="floatingPasswordConfirmation">Confirm Password</label>
            </div>
        
            
            <button class="btn btn-outline-warning w-100 py-2 mt-4" type="submit">Register</button>

            <p class="mt-3 mb-3 text-body-secondary">Already have an account? <a class="hover-effect" href="{% url 'auctions:login' %}">Log In here.</a></p>
          </form>
        </main>
        
        </div>


{% comment %} 
    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>
 {% endcomment %}


{% endblock %}

project 2 commerce/commerce/auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Watchlist</h2>
    {% for object in watchlist %}
        {% if object.listing.image %}
           <a href="{% url 'auctions:listing' object.listing.id %}"><img src="{{ object.listing.image.url }}" alt="Photo of {{object.listing.title}}"></a> 
        {% endif %}
        {{object.listing.title}}
        {{object.listing.bidCurrentPrice}}
        {{object.listing.time}}
        {% empty %}
        <h5>No Listings Watchlisted.</h5>
    {% endfor %}
    

{% endblock %}