project 1 wiki/wiki/encyclopedia/urls.py
from django.urls import path

from . import views
app_name = 'encyclopedia'

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/new", views.createNewPage, name="createNewPage"),
    path("wiki/random", views.randomPage, name="randomPage"),
    path("wiki/edit/<str:pageTitle>", views.editPage, name="editPage"),
    path("wiki/<str:pageTitle>", views.viewPage, name="viewPage")    
]

project 1 wiki/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

project 1 wiki/wiki/encyclopedia/forms.py
from django import forms

class NewSearchEntryForm(forms.Form):
    searchEntry = forms.CharField(label="",widget=forms.TextInput(attrs={'placeholder': 'Search Encyclopedia'}))

class NewPageForm(forms.Form):
    pageTitle = forms.CharField(label="Title", widget=forms.TextInput(attrs={"class":"form-group"}))
    markdownContent = forms.CharField(label="MarkDown Content", widget=forms.Textarea(attrs={"class":"form-group"}))

class NewEditForm(forms.Form):
    markdownContent = forms.CharField(label="MarkDown Content", widget=forms.Textarea(attrs={"class":"form-group"}))

project 1 wiki/wiki/encyclopedia/views.py
from django.shortcuts import render
from django.core.files.storage import default_storage
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from . import util
from .forms import NewEditForm, NewPageForm, NewSearchEntryForm
import markdown2
    

def index(request):
    if util.isMethodPost(request):
        searchEntryForm = NewSearchEntryForm(request.POST)
        if searchEntryForm.is_valid():
            searchEntry = searchEntryForm.cleaned_data["searchEntry"]
            entries = util.list_entries()
            entriesMatchingSearch = []
            for entry in entries:
                if searchEntry.lower() == entry.lower():
                    return HttpResponseRedirect(reverse("encyclopedia:viewPage", args=(entry,)))
                elif searchEntry.lower() in entry.lower():
                    entriesMatchingSearch.append(entry)

        return render(request, 'encyclopedia/index.html', {
            "entries": entriesMatchingSearch,
            "heading": "Search Results",
            "searchEntryForm": searchEntryForm
        })

    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "heading": "All Pages",
        "searchEntryForm": NewSearchEntryForm()
    })

def viewPage(request, pageTitle):
    markdownContent = util.get_entry(pageTitle)
    if markdownContent == None:
        return render(request, 'encyclopedia/errorPage.html', {
            "pageTitle" : pageTitle,
            "errorMessage": f"/wiki/{pageTitle} Page Not Found",
            "searchEntryForm": NewSearchEntryForm()
        })
    else:
        html = markdown2.markdown(markdownContent)
        return render(request, 'encyclopedia/viewPage.html', {
            "html" : html, 
            "pageTitle" : pageTitle,
            "searchEntryForm": NewSearchEntryForm()
        })
    
def createNewPage(request):
    if(util.isMethodPost(request)):
        newPageData = NewPageForm(request.POST)
        if newPageData.is_valid():
            pageTitle = newPageData.cleaned_data["pageTitle"]
            markdownContent = newPageData.cleaned_data["markdownContent"]
            if(util.isValidPageTitle(pageTitle)):
                newPageFile = default_storage.open(f"entries/{pageTitle}.md", mode="w")
                newPageFile.write(markdownContent)
                return HttpResponseRedirect(reverse("encyclopedia:viewPage" , args=(pageTitle, )))
            else:
                errorMessage = f"Page with title {pageTitle.lower()} already exists"
                return render(request, 'encyclopedia/createNewPage.html', {
                    "newPageForm" : newPageData,
                    "errorMessage": errorMessage,
                    "searchEntryForm": NewSearchEntryForm()
                })
                
    
    return render(request, 'encyclopedia/createNewPage.html',{
        "newPageForm":NewPageForm(),
        "searchEntryForm": NewSearchEntryForm(),
    })

def editPage(request, pageTitle):
    if(util.isMethodPost(request)):
        editFormData = NewEditForm(request.POST)
        if(editFormData.is_valid()):
            markdownContent = editFormData.cleaned_data["markdownContent"]
            editPageFile = default_storage.open(f"entries/{pageTitle}.md", mode="w")
            editPageFile.write(markdownContent)
            return HttpResponseRedirect(reverse("encyclopedia:viewPage", args=(pageTitle, )))
        else:
            return render(request, 'encyclopedia/editPage.html', {
                "pageTitle" : pageTitle,
                "editPageForm": editFormData,
                "searchEntryForm": NewSearchEntryForm()
            })

    return render(request, "encyclopedia/editPage.html", {
        "pageTitle":pageTitle,
        "editPageForm": NewEditForm(initial={"markdownContent":util.get_entry(pageTitle)}),
        "searchEntryForm": NewSearchEntryForm()
    })

def randomPage(request):
    pageTitle = util.getRandomPageTitle()
    return HttpResponseRedirect(reverse("encyclopedia:viewPage", args=(pageTitle, )))

project 1 wiki/wiki/encyclopedia/templates/encyclopedia/createNewPage.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    Create New Page
{% endblock %}

{% block style %}
<style>
    body form div{
        display: flex;
        flex-direction: column;
        align-items: flex-start;
    }
</style>
{% endblock %}


{% block body %}
<!-- <h1>Create New Page</h1> -->
<h1>{{ pageTitle }}</h1>
<form action="{% url 'encyclopedia:createNewPage' %}" method="post">
    {% csrf_token %}
    {{newPageForm}}
    <h5 class="text-danger">{{errorMessage}}</h3>
    <input type="submit" value="Save">
</form>

{% endblock %}

project 1 wiki/wiki/encyclopedia/templates/encyclopedia/editPage.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    {{pageTitle}} (Edit)
{% endblock %}

{% block style %}
<style>
    body form div{
        display: flex;
        flex-direction: column;
        align-items: flex-start;
    }
</style>
{% endblock %}



{% block body %}
<h1>{{pageTitle}}</h1>
<form action="{% url 'encyclopedia:editPage' pageTitle %}" method="post">
    {% csrf_token %}
    {{editPageForm | safe}}
    <input type="submit" value="Save">
</form>
{% endblock %}

project 1 wiki/wiki/encyclopedia/templates/encyclopedia/errorPage.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    {{pageTitle}}
{% endblock %}

{% block body %}

<h1 class="text-danger">ERROR</h1>
<h3 class="text-danger">{{errorMessage}}</h3>

{% endblock %}

project 1 wiki/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>{{heading}}</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:viewPage' entry %}">{{entry}}</a></li>
        {% empty %}
            <p>No Entries Found</p>
        {% endfor %}
    </ul>

{% endblock %}

project 1 wiki/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        {% block style %}
        {% endblock %}
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2><a href="{% url 'encyclopedia:index' %}" style="text-decoration: none; color: black;">Wiki</a></h2>
                <form action="{% url 'encyclopedia:index' %}" method="post">
                    {% csrf_token %}
                    {{searchEntryForm}}
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:createNewPage' %}">Create New Page</a>
                </div>
                
                <div>
                    <a href="{% url 'encyclopedia:randomPage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
                
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

project 1 wiki/wiki/encyclopedia/templates/encyclopedia/viewPage.html
{% extends 'encyclopedia/layout.html' %}

{% block nav %}
<div>
    <a href="{% url 'encyclopedia:editPage' pageTitle %}">Edit Page</a>
</div>
{% endblock %}

{% block title %}
    {{pageTitle}}
{% endblock %}



{% block body %}

{{html | safe}}

{% endblock %}