lecture 7 testing and ci/airline0/flights/urls.py
from django.urls import path
from . import views

app_name = "flights"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:flight_id>/", views.displayFlightInformation, name="displayFlightInformation"),
    path("<int:flight_id>/book", views.book, name="book")
]

lecture 7 testing and ci/airline0/flights/models.py
from django.db import models

# Create your models here.
class Airport(models.Model):
    code = models.CharField(max_length=3)
    city = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.city} ({self.code})"
    

class Flight(models.Model):
    origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="departures")
    destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="arrivals")
    duration = models.IntegerField()

    def __str__(self):
        return f"{self.id}: {self.origin} to {self.destination}"
    
    def is_valid_flight(self):
        return self.origin != self.destination and self.duration>0
    
class Passenger(models.Model):
    first = models.CharField(max_length=64)
    last = models.CharField(max_length=64)
    flights = models.ManyToManyField(Flight, blank=True, related_name="passengers")

    def __str__(self):
        return f"{self.first} {self.last}"

lecture 7 testing and ci/airline0/flights/views.py
from django.shortcuts import render
from .models import Flight, Passenger
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
# Create your views here.
def index(request):
    return render(request, "flights/index.html", {
        "flights":Flight.objects.all()
    })

def displayFlightInformation(request, flight_id):
    try:
        flight = Flight.objects.get(pk = flight_id)
    except:
        raise Http404()
    
    return render(request, "flights/flight.html", {
        "flight" : flight,
        "passengers" : flight.passengers.all(),
        "non_passengers" : Passenger.objects.exclude(flights = flight).all()
    })

def book(request, flight_id):
    if request.method == "POST":
        flight = Flight.objects.get(pk = flight_id)
        passenger = Passenger.objects.get(pk = int(request.POST["foo"]))
        passenger.flights.add(flight)
        return HttpResponseRedirect(reverse("flights:displayFlightInformation", args=(flight.id, )))
    

lecture 7 testing and ci/airline0/flights/templates/flights/flight.html
{% extends 'flights/layout.html' %}

{% block body %}
<h1>Flight No. {{flight.id}}</h1>
<h3>Origin: {{flight.origin}}</h3>
<h3>Destination: {{flight.destination}}</h3>
<h3>Duration: {{flight.duration}}</h3>

<h1>Passengers</h1>
<ul>
    {% for passenger in passengers %}
        <li>{{ passenger }}</li>
    {% empty %}
        <li>No passengers.</li>
    {% endfor %}
</ul>

<h1>Add Passengers</h1>
<form action="{% url 'flights:book' flight.id %}" method="post">
    {% csrf_token %}
    <select name="foo">
        {% for passenger in non_passengers %}
            <option value="{{passenger.id}}">{{passenger}}</option>
        {% endfor %}
    </select>
    <input type="submit" >
</form>

<a href="{% url 'flights:index' %}">Back to Home Page</a>
{% endblock %}

lecture 7 testing and ci/airline0/flights/templates/flights/index.html
{% extends "flights/layout.html" %}

{% block body %}
<h1>Flights</h1>
<ul>
    {% for flight in flights %}
    <li><a href="{% url 'flights:displayFlightInformation' flight.id %}">Flight {{ flight.id }}: {{ flight.origin }} to
            {{ flight.destination }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

lecture 7 testing and ci/airline0/flights/templates/flights/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flights</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>